### ISSUE TITLE
label:invalid $bananas protocol link broken

### ISSUE THREAD

**Issue by unclemantis** [boomcrypto/clarity-deployed-contracts#10]
[Page containing bad link](https://clarity-deployed-contracts.netlify.app/protocols/bananas/#) 
[Correct link](https://github.com/boomcrypto/clarity-deployed-contracts/blob/main/contracts/SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C/bitcoin-monkeys-bananas.clar) 
[Current BAD link](https://github.com/boomcrypto/clarity-deployed-contracts/blob/main/contracts/SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C/bitcoin-monkeys-bananas.clar.clar)

**Comment by friedger** [comment]
Has been fixed. Thank you for reporting!
